#!/bin/bash

RED="\033[1;31m"
YELLOW="\033[1;33m"
NC="\033[0m" # No Color


printf "${YELLOW}"
while read line
do
  l1=${line//$'\t'/$'\n'${RED}}
  printf "${l1//=/${NC} = }\n"
  printf "${YELLOW}~~~~~~~~~~~~~~~~\n"
done < "${1:-/dev/stdin}"
